name: goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    uses: libops/.github/.github/workflows/sitectl-plugin-goreleaser.yaml@8cdff451294d4663695a9f326ec3a38ddd87f573 # main
    permissions:
      contents: write
      id-token: write
    secrets: inherit
    with:
      go-version: ">=1.26.1"
      package-name: sitectl-drupal
